# Generated by Django 5.0.1 on 2024-02-02 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_file_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='data',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
